### ISSUE TITLE
Where is the repo?

### ISSUE THREAD

**Issue by dangbert** [winycg/CLIP-KD#1]
This paper references this repo but there's nothing here.

https://arxiv.org/abs/2307.12732

**Comment by winycg** [comment]
Thanks for your attention of our work. Because our paper have not been published and works in progress, we have not released our code. If our work is comprehensive and finished, we will release code.

**Comment by winycg** [comment]
Hi, we have released code and pretrained models. Please feel free to ask any questions if you find any problems.
