### ISSUE TITLE
AFD and CRD launch scripts are the same in the README

### ISSUE THREAD

**Issue by vishaal27** [winycg/CLIP-KD#10]
Hey, 
Thanks for your great work and for publicly releasing the code. I just noticed that in the first table, the [AFD](https://github.com/winycg/CLIP-KD/blob/main/script/methods/AFD.sh) and [CRD](https://github.com/winycg/CLIP-KD/blob/main/script/methods/CRD.sh) launch scripts are exactly the same. Could you please verify if this is indeed a mistake?

**Comment by winycg** [comment]
Thank you for pointing this problem. I have fixed this mistake by replace  "alpha_ckd_loss"with "alpha_afd_loss".
