### ISSUE TITLE
Request for links of downloading CC12M

### ISSUE THREAD

**Issue by jwfanDL** [winycg/CLIP-KD#11]
Thanks a lot for releasing the amazing code.

I had some problems downloading CC12M by scripts. I'll appreciate it if you can provide hyperlinks, similar to CC3M in previous issues.

**Comment by Han-jiaxin** [comment]
same issue

**Comment by winycg** [comment]
The cc12m dataset can be downloaded from [https://pan.baidu.com/s/1QVc0QBWPoNC2Ta1c1hbE8Q?pwd=1234](https://github.com/winycg/CLIP-KD/issues/url)
