### ISSUE TITLE
Problem for collecting CC3M

### ISSUE THREAD

**Issue by cjw0426** [winycg/CLIP-KD#14]

**Comment by cjw0426** [comment]
python src/data/gather_cc.py [path/to/cc3m/images/] [path/to/cc3m_train.tsv] [path/to/cc3m_val.tsv]
When I run this, I can't get the datasets,and I will get "Unknown error HTTPSConnectionPool"

**Comment by cjw0426** [comment]
python src/data/gather_cc.py [path/to/cc3m/images/] [path/to/cc3m_train.tsv] [path/to/cc3m_val.tsv]
When I run this, I can't get the datasets,and I will get "Unknown error HTTPSConnectionPool"

**Comment by winycg** [comment]
Hi, this problem seems having an Internet error or the link of the image is not available.
Alternative, you may download the CC3M dataset from the Baidu Drive:
链接: https://pan.baidu.com/s/19AOZboIJwXwtXUGkzbNNZQ?pwd=gew4 提取码: gew4
