### ISSUE TITLE
Some questions on evaluating on MS-COCO and Flicker

### ISSUE THREAD

**Issue by jwfanDL** [winycg/CLIP-KD#16]
First of all, thank you for releasing the code. However, I encountered some problems when I tried to evaluate it on MS-COCO and Flicker.   It seems that the captions are saved in a .pt file, and image keys are saved in a .tsv file. 

When I run the program, the following issues occured. 

![image](https://github.com/user-attachments/assets/b9a8e31f-3c03-4019-baa3-6a8c500c112c)

The two files are self-generated or downloaded from other website.  

Thank you for your time, and I am looking forward to your reply!

Best regards,
Jiawei

**Comment by winycg** [comment]
Hi, thanks for your attention to this work. I will attempt to release the related datasets about CC12M, COCO, Flicker!
