### ISSUE TITLE
questions about the attention head

### ISSUE THREAD

**Issue by xushilin1** [winycg/CLIP-KD#4]
In the Feature Distillation section, you use MSE loss to reduce the distance between the text embeddings of the student and teacher. I notice that you use different attention-heads (8 for teacher and 6 for student).

I want to know if it's better to maintain consistency in the attention head, like forcefully changing the student's head to 8.

**Comment by winycg** [comment]
Sorry for the late response. In the default setup, we use the final output text embeddings for feature distillation. If the embedding size between the teacher and student is dismatch, we apply a projection head to transform the student embedding to match the size of the teacher's embeding.

**Comment by winycg** [comment]
Hi, we have released code and pretrained models. Please feel free to ask any questions if you find any problems.
