### ISSUE TITLE
CC3M数据集

### ISSUE THREAD

**Issue by WangYZ1608** [winycg/CLIP-KD#7]
亲爱的作者，你好。
祝贺你们的工作发表在了CVPR2024。
我尝试下载CC3M数据集，但是发现和在README里所说的数据相差很多，我下载的成功只有8千多张（验证集） vs. 1.3M README.
请问作者能否把下载的数据集分享出来呢？
感谢！！！

**Comment by winycg** [comment]
链接: https://pan.baidu.com/s/19AOZboIJwXwtXUGkzbNNZQ?pwd=gew4 提取码: gew4
