### ISSUE TITLE
The performance when abandoning task loss

### ISSUE THREAD

**Issue by youngtboy** [winycg/CLIP-KD#8]
This is a comprehensive experimental study, but I have a question: if we abandon task loss (CLIP Pretrain Loss) and only use distillation loss (such as FD), how does the performance compare to the provided results?

**Comment by vishaal27** [comment]
Yes I have the same question---I think this would be much worse than the baseline since there would not be any explicit objective for doing image-text matching. But it would good to verify this empirically.

**Comment by winycg** [comment]
Sorry for the delay response. I have conducted experiments about ablating the task loss but only retaining the distillation losses of CRD, FD, and ICL. As shown in the table, the result without the task loss achieves 40.1% accuracy on ImageNet, leading to a 2.5% drop compared to the original CLIP-KD with task loss.


Role | Network | Method | ImageNet | 
-- | -- | -- | -- | 
Teacher | ViT-B/16 | - | 67.1 | 
Student | ViT-T/16 | Baseline | 30.6 | 
Student | ViT-T/16 | CLIP-KD (W/O task loss) | 40.1 | 
Student | ViT-T/16 | CLIP-KD | 42.6 |
